kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'html-openshift-app:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nginx:1.20-ubi7'
  source:
    type: Git
    git:
      uri: 'https://github.com/lucaom448/uk109.git'
    contextDir: /Projects/Block-6/Auftrag-6.2/app
    SourceSecret:
      name: webhook-secret
  triggers:
    - type: Generic
      generic:
          secretReference:
            name: webhook-secret
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial