kind: Deployment
apiVersion: apps/v1
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-openshift-app
  template:
    metadata:
      labels:
        app: html-openshift-app
    spec:
      volumes:
        - name: html-openshift-app-data
          persistentVolumeClaim:
            claimName: html-openshift-app
      containers:
      - name: html-openshift-app
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          protocol: TCP
        image: ghcr.io/lucaom448/uk109/html-openshift-app:v1
        imagePullPolicy: Always