kind: Secret
apiVersion: v1
metadata:
  name: webhook-secret
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  WebHookSecretKey: YjI4ZWJiNzQ4MWQ1ZGFkNA==
type: Opaque
