apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-database
  labels:
    app: counter-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-database
  template:
    metadata:
      labels:
        app: counter-database
    spec:
      containers:
        - name: counter-database
          image: registry.redhat.io/rhel8/postgresql-15:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-name
          volumeMounts:
            - name: counter-database-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: counter-database-data
          persistentVolumeClaim:
            claimName: counter-database-data

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-backend
  labels:
    app: counter-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-backend
  template:
    metadata:
      labels:
        app: counter-backend
    spec:
      containers:
        - name: counter-backend
          image: 'registry.gitlab.com/ahmadshoaib.muhebali/uek109-ahmad/counter-backend:v1'
          imagePullPolicy: IfNotPresent
          resources: 
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200m
          env:
            - name: npm_config_cache
              value: ./.npm-cache
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-password
          ports:
            - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-frontend
  labels:
    app: counter-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-frontend
  template:
    metadata:
      labels:
        app: counter-frontend
    spec:
      containers:
        - name: counter-frontend
          image: 'registry.gitlab.com/ahmadshoaib.muhebali/uek109-ahmad/counter-frontend:v1'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200m
          env:
            - name: npm_config_cache
              value: ./.npm-cache
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BACKEND_URL
              value: https://counter-backend-254201-zlic-loconnor1.apps.exoscale-ch-gva-2-0.appuio.cloud
          ports:
            - containerPort: 3000